// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Pathfinding.Serialization
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class ChunkDataFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Pathfinding.Serialization.ChunkData>
    {


        public void Serialize(ref MessagePackWriter writer, global::Pathfinding.Serialization.ChunkData value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(2);
            formatterResolver.GetFormatterWithVerify<global::Pathfinding.Node[,,]>().Serialize(ref writer, value.gridNodes, options);
            formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.Dictionary<global::UnityEngine.Vector3, global::Pathfinding.Node>>().Serialize(ref writer, value.graphNodes, options);
        }

        public global::Pathfinding.Serialization.ChunkData Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __gridNodes__ = default(global::Pathfinding.Node[,,]);
            var __graphNodes__ = default(global::System.Collections.Generic.Dictionary<global::UnityEngine.Vector3, global::Pathfinding.Node>);

            for (int i = 0; i < length; i++)
            {
                var key = i;

                switch (key)
                {
                    case 0:
                        __gridNodes__ = formatterResolver.GetFormatterWithVerify<global::Pathfinding.Node[,,]>().Deserialize(ref reader, options);
                        break;
                    case 1:
                        __graphNodes__ = formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.Dictionary<global::UnityEngine.Vector3, global::Pathfinding.Node>>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Pathfinding.Serialization.ChunkData(__gridNodes__, __graphNodes__);
            ____result.gridNodes = __gridNodes__;
            ____result.graphNodes = __graphNodes__;
            reader.Depth--;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
